/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebar = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
   
};

const sidebar2 = {
  docs:[
    {
      type:'doc',
      id:'introduccion',
      label:'Introducción',
        
    },  
    { 
      type:'doc',
      id:'estandarCodigo',
      label:'Estándares de Código',
    }, 
    { 
      type:'doc',
      id:'stack',
      label:'Stack de tecnología'
    },
    { 
      type:'doc',
      id:'ambienteLocal',
      label:'Ambiente Local',
    },
    {
      type:'doc',
      id:'ambienteProduccion',
      label:'Ambiente de Producción',
    },
    {
      type:'doc',
      id:'pruebas',
      label:'Plan de Pruebas',
    },
  ]
};

module.exports = sidebar2;
